markdown:         rdiscount
pygments:         true
paginate:         4

title:            Black Cube Theme
url:              http://zixiaojindao.github.com
feed:             /atom.xml
author:
    name:         whitewater 
    email:        zixiaojindao@gmail.com
description:      "whitewater's blog"

about: 			  "I am whitewater.I love all kinds of beauty" 
follow:
    github:       https://github.com/zixiaojindao
    twitter:      http://weibo.com/1896913847/profile 
description:      "whitewater's blog"


style: 			  /css/style.css
blogName: 		  whitewater 
blogDesc: 		  …œ…∆»ÙÀÆ 
